### PR TITLE
Add pybullet to `requirements-dev.txt`

### PR DESCRIPTION
**Pull request by toslunar**
After #371 the tests require pybullet.

### CODE REVIEW

**Comment by toslunar** [comment]
imosci test this please

**Comment by ninetan** [comment]
imosCI successfully created a job for commit 228d9cd:
- [**Dashboard for commit 228d9cd**](https://pfn-public-ci.appspot.com/p/dashboard_by_commit_id?commit_id=228d9cdb28c95753dc4793ebba1dcc62da7b09e1)

**Review by prabhatnagarajan — APPROVED** [review]
LGTM

**Pull request merged**
