### PR TITLE
Drops Chainer V4 Support

### PR DESCRIPTION
**Pull request by prabhatnagarajan**
- My demonstration collection (https://github.com/chainer/chainerrl/pull/468) PR is blocked because the CI is failing due to the use of functionality that is not supported in Chainer V4
- https://travis-ci.org/chainer/chainerrl/jobs/545265192

This drops support for Chainer V4.

### CODE REVIEW

**Comment by toslunar** [comment]
Could you address my comment (in an internal discussion, last month).

> Currently, the support for Chainer v4 helps us to check mistakes in automatic broadcasts.
> Example: https://github.com/prabhatnagarajan/chainerrl/commit/ed0189ae23dc445fa831a5d41e12c9e5b304fdf4
> Before dropping Chainer v4, I'd like to avoid `axis=None`.

**Comment by keisuke-nakata** [comment]
Travis error `AttributeError: 'ALEInterface' object has no attribute 'getAvailableModes'` was fixed in #492 .
Could you merge/rebase the latest master?

**Comment by keisuke-nakata** [comment]
I found Chainer v4 in `requirements.txt`. Could you fix that?

**Comment by toslunar** [comment]
I can takeover the PR.

**Pull request closed without merging**
