### PR TITLE
Add config files for imosCI tests.

### PR DESCRIPTION
**Pull request by imos**
This will enable the following test projects:
- chainerrl.py2.old-chainer ... https://pfn-public-ci.appspot.com/chainerrl.py2.old-chainer/78/
- chainerrl.py2.stable-chainer ... https://pfn-public-ci.appspot.com/chainerrl.py2.stable-chainer/79/
- chainerrl.py3.gpu ... https://pfn-public-ci.appspot.com/chainerrl.py3.gpu/77/
- chainerrl.py3.old-chainer ... https://pfn-public-ci.appspot.com/chainerrl.py3.old-chainer/74/
- chainerrl.py3.stable-chainer ... https://pfn-public-ci.appspot.com/chainerrl.py3.stable-chainer/73/

### CODE REVIEW

**Comment by toslunar** [comment]
imosci test this please

**Comment by ninetan** [comment]
imosCI successfully created a job for commit 3768c90:
- [**Dashboard for commit 3768c90**](https://pfn-public-ci.appspot.com/p/dashboard_by_commit_id?commit_id=3768c9034839cca2f7820cacc2482904906865f7)

**Comment by toslunar** [comment]
Can I close the PR because #478 is merged?

**Comment by muupan** [comment]
Yes let's close.

**Pull request closed without merging**
